version: '3.9'

services:
  db:
    image: postgres:alpine
    container_name: db-pix
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pix
    ports:
      - "5432:5432"