version: '3.9'

services:

  db:
    image: postgres:alpine
    container_name: db-chavepix
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chavepix
    ports:
      - "5432:5432"

  bcb:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    ports:
      - 8082:8082

  erp-itau:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    ports:
      - 9091:9091