
micronaut:
  application:
    name: key-manager-grpc

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/chavepix
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update

clients:
  itau: http://localhost:9091/api/v1
  banco-central: http://localhost:8082/api/v1/pix
